import { AntdRegistry } from "@ant-design/nextjs-registry";
import Link from "next/link";
import { ADLaM_Display } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  team,
  analysis,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analysis: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <div
            className="container mx-auto"
            style={{ border: "1px solid red" }}
          >
            <div
              className="flex justify-center text-blue-500 p-6 gap-6"
              style={{
                display: "flex",
                gap: "20px",
                justifyContent: "center",
                fontSize: "20px",
              }}
            >
              <Link href="/" style={{ color: "lightblue" }}>
                Home
              </Link>
              <Link href="/visitor">Visitor</Link>
            </div>
            <div
              className="flex gap-6"
              style={{
                display: "flex",
                padding: "20px",
                justifyContent: "space-between",
              }}
            >
              {team}
              {analysis}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
